### ISSUE TITLE
FutureWarning regarding bool checking in enum.py

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-core#100]
Following warning is generated when running tests on GitHub:

```
policyengine_us/tests/microsimulation/test_microsim.py: 3 warnings
  /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/policyengine_core/enums/enum.py:74: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    if isinstance(array == 0, bool):
```

Code:
https://github.com/PolicyEngine/policyengine-core/blob/e41f19a6c43954d8b737483b34a5e9af34312763/policyengine_core/enums/enum.py#L74-L75

**Comment by MaxGhenis** [comment]
[ChatGPT suggested either `np.any` or `np.all`](https://chat.openai.com/share/2e48436a-55e9-4e17-aa35-88caf5df4168)
