### ISSUE TITLE
Support `adds = "float_or_int_policy_parameter"`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#102]
For example, https://github.com/PolicyEngine/policyengine-us/pull/2306 involves a `nh_total_exemptions` variable which sums several individual exemption variables using `adds=[]`, and one of those is a `nh_base_exemption` which is a flat amount. So it'd be easier to avoid a `formula` just to return a parameter value.

**Comment by PavelMakarchuk** [comment]
> For example, [PolicyEngine/policyengine-us#2306](https://github.com/PolicyEngine/policyengine-us/pull/2306) involves a `nh_total_exemptions` variable which sums several individual exemption variables using `adds=[]`, and one of those is a `nh_base_exemption` which is a flat amount. So it'd be easier to avoid a `formula` just to return a parameter value.

Also [PolicyEngine/policyengine-canada#397](https://github.com/PolicyEngine/policyengine-canada/pull/397)
