### ISSUE TITLE
New changes break parametric reforms in US model

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#130]
PRs #127 and/or #128 fixed bugs that affected UK microsimulation accuracy with respect to uprating and reforms, but caused the US one to break entirely (https://github.com/PolicyEngine/policyengine-us/issues/3311).

**Comment by MaxGhenis** [comment]
The app and policyengine-us package are now OK.

[The UK Autumn Statement benefit uprating change](https://policyengine.org/uk/policy?focus=policyOutput.netIncome&timePeriod=2024&region=uk&reform=1&baseline=37721) isn't completing, as we've pinned to a version of policyengine-core that probably didn't support that.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff can we close this given your handling of the issue in policyengine-us?

**Comment by nikhilwoodruff** [comment]
Yes- just verified on the live site
