### ISSUE TITLE
Assert that only one of a formula or adds/subtracts pairs defines a variable

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#139]
If a variable has a formula, there should be no adds/subtracts, and each variable should have at most one adds/subtracts.

**Comment by abhcs** [comment]
> If a variable has a formula, there should be no adds/subtracts

Is the reverse also true, i.e., if a variable has adds/subtracts, there should be no formula?

I can add a class method that tests this property. This method then will need to be called for all variables in the CI tests in -us, -uk, etc.

> each variable should have at most one adds/subtracts

This is already enforced. The last `adds` overwrites the previous `adds` -- this is a feature of Python. Ensuring that overwrites are not used is best handled through code reviews.

**Comment by MaxGhenis** [comment]
>Is the reverse also true, i.e., if a variable has adds/subtracts, there should be no formula?

yes

**Comment by nikhilwoodruff** [comment]
OK so we should revert this right @MaxGhenis?
