### ISSUE TITLE
Uncap coverage

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#186]
Currently <7:

https://github.com/PolicyEngine/policyengine-core/blob/4c67661f0e7e23d526f5bc99af91f8b54a9bd0c9/setup.py#L18

But it's now on 7.4.4: https://pypi.org/project/coverage/

**Comment by Suvid-Singhal** [comment]
To fix this issue, should I just remove the "<7" part? Or should I replace it with "<8"?
