### ISSUE TITLE
Drop Python 3.9 support

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-core#244]
The following line 6 does not work under Python 3.9 because the `|` notation for `Union` was introduced into Python `typing` beginning with Python 3.10.

https://github.com/PolicyEngine/policyengine-core/blob/47f5bdf953d8c6776f9af1f3859864c12ebbf36f/policyengine_core/types/data_types/arrays.py#L1-L6

I suggest revising `setup.py` to require Python 3.10, 3.11, or 3.12.

**Comment by anth-volk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix UK policy calculator failing](https://trello.com/c/nHHeWfLb/4-fix-uk-policy-calculator-failing)

**Comment by anth-volk** [comment]
Closed as part of #286.
