### ISSUE TITLE
Import microdf rather than recreating its classes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#245]
We should do this after slimming down the microdf package to just MicroSeries and MicroDataFrame (removing visualization and analysis features)

**Comment by anth-volk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix UK policy calculator failing](https://trello.com/c/nHHeWfLb/4-fix-uk-policy-calculator-failing)

**Comment by anth-volk** [comment]
As a start, we can also conditionally import `matplotlib` and `seaborn`, which I'll have a PR open for soon.
