### ISSUE TITLE
Move jupyter-book requirement in setup.py

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-core#247]
Move the `"jupyter-book<1"` requirement from the `dev_requirements` list (line 33 below) to the `general_requirements` list.   This move is needed because country models have CI documentation tests that will fail unless `jupyter-book` is available.

https://github.com/PolicyEngine/policyengine-core/blob/47f5bdf953d8c6776f9af1f3859864c12ebbf36f/setup.py#L12-L46

**Comment by nikhilwoodruff** [comment]
In that case those country models should have Jupyter-book in their dev dependencies. PolicyEngine US [has](https://github.com/PolicyEngine/policyengine-us/blob/master/setup.py) it, so closing!
