### ISSUE TITLE
Raise DivisionByZeroError when calls to microdf result in division by zero

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-core#255]
This is linked to https://github.com/PolicyEngine/policyengine-uk/issues/928. In situations where a sim or microsim attempts to use `microdf`'s `MicroSeries` class, `rank` method with an array of weights that equal 0, `core` should raise an error. This is because the `rank` method will attempt to divide by the sum of all values within the weights array, be unable to divide, and return an array of `nan` values.

**Comment by MaxGhenis** [comment]
Should this be in microdf? Since this involves the additional weighting functionality, not just core pandas replication.

**Comment by anth-volk** [comment]
Definitely

**Comment by anth-volk** [comment]
Closing in light of https://github.com/PSLmodels/microdf/issues/233
