### ISSUE TITLE
When calculating impacts of structural reforms, the line in the varying your earnings chart is not correct

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-core#287]
This seems to appear sporadically and only when returning to the chart multiple times 

![image](https://github.com/user-attachments/assets/c60f3f30-a653-44ce-a9c7-37335af4423f)

**Comment by anth-volk** [comment]
Transferred from `-app` as the bug causing this lies in `-core`.

**Comment by anth-volk** [comment]
The best place to create a test would actually be the API, as reproducing requires multiple runs and a `CountryTaxBenefitSystem` instance, hence the issue opened to do so.
