### ISSUE TITLE
Bug in Dataset constructor

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-core#30]
When trying to instantiate a Dataset object (in the same way I was successfully doing before the model-name-change process was undertaken), I get the following error message:

```
Traceback (most recent call last):
.
.
.
  File "//Users/mrh/anaconda3/envs/policyengine-us/lib/python3.9/site-packages/policyengine_core/data/dataset.py", line 41, in __init__
    if not self.folder_path.exists():
AttributeError: 'str' object has no attribute 'exists'
```

The error message says it all:  a string (`folder_path`) does not have an `exists` method.  

If you are trying to check the existence of the `folder_path`, then try something like this:
```
if not os.path.exists(self.folder_path):
```

**Comment by nikhilwoodruff** [comment]
Thanks for filing Martin- hopefully this is fixed for you now (works for me). Feel free to reopen if not.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #30:
> Thanks for filing Martin.  Hopefully this is fixed for you now (works for me).

Thanks.  Yes, it is working for me now that I have figured out all the changes in the Microsimulation class constructor's arguments and the changes to the Microsimulation class calculate method's arguments.
