### ISSUE TITLE
Relax pytest version requirements

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#32]
Per https://github.com/PolicyEngine/policyengine-uk/issues/645, pytest version requirements are causing conflicts.

[We restrict the version range](https://github.com/PolicyEngine/policyengine-core/blob/master/setup.py#L13) in a way that mirrors [openfisca-core](https://github.com/openfisca/openfisca-core/blob/master/setup.py#L19). Can we uncap the version?

**Comment by nikhilwoodruff** [comment]
De-assigning for now because I think this is quite complex and not an immediate prioriy
