### ISSUE TITLE
Throw descriptive error when `adds` and `subtracts` encounter non-existent variable names

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-core#66]
cc @MaxGhenis

**Comment by martinholmer** [comment]
@nikhilwoodruff,  when is issue #66 going to be fixed?
It's been open for over one year now.  And it is causing problems for developers.

**Comment by nikhilwoodruff** [comment]
Thanks for the reminder @martinholmer - I'll fix this tomorrow.
