### ISSUE TITLE
Add venv to .gitignore

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#72]
Some users may want to make a `venv` (and we may want to suggest this), so ignoring contents will avoid git issues there.

For posterity, steps would be something like
```shell
pyenv shell 3.9.16 
python -m venv venv  
```
cc @ibushong

**Comment by ibushong** [comment]
Highly recommend adding pyenv and venv setup instructions, though it should be optional since many users will have their own flows.
